/**
 *
 * Copyright (c) 2026, Openflexo
 *
 * This file is part of Free-modelling-editor, a component of the software infrastructure
 * developed at Openflexo.
 *
 *
 * Openflexo is dual-licensed under the European Union Public License (EUPL, either
 * version 1.1 of the License, or any later version ), which is available at
 * https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 * and the GNU General Public License (GPL, either version 3 of the License, or any
 * later version), which is available at http://www.gnu.org/licenses/gpl.html .
 *
 * You can redistribute it and/or modify under the terms of either of these licenses
 *
 * If you choose to redistribute it and/or modify under the terms of the GNU GPL, you
 * must include the following additional permission.
 *
 *          Additional permission under GNU GPL version 3 section 7
 *
 *          If you modify this Program, or any covered work, by linking or
 *          combining it with software containing parts covered by the terms
 *          of EPL 1.0, the licensors of this Program grant you additional permission
 *          to convey the resulting work. *
 *
 * This software is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.
 *
 * See http://www.openflexo.org/license.html for details.
 *
 *
 * Please contact Openflexo (openflexo-contacts@openflexo.org)
 * or visit www.openflexo.org if you need additional information.
 *
 */

package org.openflexo.fme.model;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.openflexo.fib.binding.FMLControlledComponent;
import org.openflexo.foundation.fml.FlexoConcept;
import org.openflexo.foundation.fml.rm.FIBComponentResource;
import org.openflexo.foundation.fml.rt.FlexoConceptInstance;
import org.openflexo.gina.model.FIBComponent;
import org.openflexo.gina.model.FIBContainer;
import org.openflexo.gina.utils.FIBInspector;
import org.openflexo.pamela.validation.ValidationError;
import org.openflexo.pamela.validation.ValidationReport;

/**
 * What a concept generated by the free modelling editor exposes as its inspector: a <code>.inspector</code> component of its container,
 * which resolves, loads, and whose bindings are all valid once bound to the concept - the way the platform shows it.
 */
public class FMEInspectorAssertions {

	private FMEInspectorAssertions() {
	}

	/**
	 * Asserts that supplied concept resolves <code>&lt;ConceptName&gt;.inspector</code> in its container, that the component loads as an
	 * inspector, that its bindings are valid once bound to the concept, and that it shows exactly the expected widgets, in that order.
	 *
	 * @return the component, bound to the concept
	 */
	public static FIBComponent assertInspectorIsValid(FlexoConcept concept, String... expectedWidgetNames) {

		String expectedFileName = concept.getName() + ".inspector";

		// An explicit @Inspector("...") - not the naming convention alone (CORE-F-4: a later rename would silently orphan a
		// component resolved only by convention). FMEInspectorGenerator#update writes it from the concept's very creation.
		assertTrue(concept.getName() + " resolves its inspector by the naming convention alone, not an explicit @Inspector(...)",
				concept.hasMetaData(FlexoConcept.INSPECTOR_METADATA));

		assertNotNull("Concept " + concept.getName() + " resolves no inspector", concept.getInspectorComponentResource());
		String uri = concept.getInspectorComponentResource().getURI();
		assertEquals(expectedFileName, uri.substring(uri.lastIndexOf('/') + 1));

		FIBComponentResource resource = concept.getInspectorComponentFlexoResource();
		assertNotNull("The inspector of " + concept.getName() + " is not a registered resource", resource);
		assertEquals(concept.getInspectorComponentResource(), resource.getIODelegate().getSerializationArtefactAsResource());
		assertSame(resource, FMEInspectorGenerator.ownInspectorResource(concept));

		// Bound to its concept, as the platform inspector shows it: 'data' is typed by the concept, and the bindings are parsed as FML
		FIBComponent component = FMLControlledComponent.loadInspectorComponent(concept, null);
		assertNotNull(expectedFileName + " did not load", component);
		assertTrue(expectedFileName + " loaded as a " + component.getClass(), component instanceof FIBInspector);

		ValidationReport report;
		try {
			report = component.validate();
		} catch (InterruptedException e) {
			throw new AssertionError("Validation of " + expectedFileName + " interrupted", e);
		}
		for (ValidationError<?, ?> error : report.getAllErrors()) {
			System.out.println("Invalid binding in " + expectedFileName + ", " + error.getValidable() + ": "
					+ report.getValidationModel().localizedIssueDetailedInformations(error));
		}
		assertEquals(expectedFileName + " has invalid bindings", 0, report.getErrorsCount());

		assertEquals(Arrays.asList(expectedWidgetNames), widgetNames(component));

		return component;
	}

	/**
	 * Asserts that supplied GR concept hands inspection entirely to its conceptual counterpart - a plain concept or a relationship,
	 * found through {@link FMEFreeModel#CONCEPT_ROLE_NAME} - rather than resolving an inspector of its own:
	 * <code>@Inspector(derived=fmeConcept)</code> is declared, and neither the naming convention nor an explicit filename key
	 * resolves any component for it (see {@link FlexoConcept#getInspectorComponentResource()} and CORE-F-4's exclusivity rule).
	 */
	public static void assertDerivesToConceptualInspector(FlexoConcept grConcept) {
		assertTrue(grConcept.getName() + " does not declare @Inspector(derived=...)", grConcept.hasDerivedInspector());
		assertNull(grConcept.getName() + " should have no inspector component of its own",
				FMEInspectorGenerator.ownInspectorResource(grConcept));
		assertNull(grConcept.getName() + " should resolve no inspector component at all",
				grConcept.getInspectorComponentResource());
	}

	/**
	 * Same as {@link #assertDerivesToConceptualInspector(FlexoConcept)}, and additionally checks that a live instance of the GR
	 * concept actually redirects: {@link FlexoConceptInstance#getInspectedObject()} on it returns the conceptual instance its
	 * {@link FMEFreeModel#CONCEPT_ROLE_NAME} role points to, not itself.
	 */
	public static void assertDerivesToConceptualInspector(FlexoConceptInstance grInstance) {
		assertDerivesToConceptualInspector(grInstance.getFlexoConcept());
		FlexoConceptInstance conceptualInstance = grInstance.getFlexoPropertyValue(FMEFreeModel.CONCEPT_ROLE_NAME);
		assertNotNull("No " + FMEFreeModel.CONCEPT_ROLE_NAME + " instance to derive to", conceptualInstance);
		assertSame("getInspectedObject() does not redirect to the conceptual instance", conceptualInstance,
				grInstance.getInspectedObject());
	}

	/**
	 * The names of the widgets of supplied component, labels left out, in order
	 */
	public static List<String> widgetNames(FIBComponent component) {
		List<String> returned = new ArrayList<>();
		if (component instanceof FIBContainer) {
			for (FIBComponent child : ((FIBContainer) component).getSubComponents()) {
				if (child.getName() != null && !child.getName().endsWith("Label")) {
					returned.add(child.getName());
				}
			}
		}
		return returned;
	}
}
